global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'host-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox-200-code-services'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://wp-0.iurii.test.monitoring.intellij.net/
        - http://wp-1.iurii.test.monitoring.intellij.net/
        - http://wp-2.iurii.test.monitoring.intellij.net/
        - http://wp-3.iurii.test.monitoring.intellij.net/
        - http://wp-4.iurii.test.monitoring.intellij.net/
        - http://wp-5.iurii.test.monitoring.intellij.net/
        - http://wp-6.iurii.test.monitoring.intellij.net/
        - http://wp-7.iurii.test.monitoring.intellij.net/
        - http://wp-8.iurii.test.monitoring.intellij.net/
        - http://wp-9.iurii.test.monitoring.intellij.net/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'blackbox-dns-monitor'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [dns_probe]
    relabel_configs:
    # Populate domain label with domain portion of __address__
    - source_labels: [__address__]
      regex: (.*):.*$
      replacement: $1
      target_label: domain
    # Populate instance label with dns server IP portion of __address__
    - source_labels: [__address__]
      regex: .*:(.*)$
      replacement: $1
      target_label: instance
    # Populate module URL parameter with domain portion of __address__
    # This is a parameter passed to the blackbox exporter
    - source_labels: [domain]
      target_label: __param_module
    # Populate target URL parameter with dns server IP
    - source_labels: [instance]
      target_label: __param_target
    # Populate __address__ with the address of the blackbox exporter to hit
    - target_label: __address__
      replacement: blackbox:9115
      
    static_configs:
      - targets:
        - http://wp-0.iurii.test.monitoring.intellij.net/
        - http://wp-1.iurii.test.monitoring.intellij.net/
        - http://wp-2.iurii.test.monitoring.intellij.net/
        - http://wp-3.iurii.test.monitoring.intellij.net/
        - http://wp-4.iurii.test.monitoring.intellij.net/
        - http://wp-5.iurii.test.monitoring.intellij.net/
        - http://wp-6.iurii.test.monitoring.intellij.net/
        - http://wp-7.iurii.test.monitoring.intellij.net/
        - http://wp-8.iurii.test.monitoring.intellij.net/
        - http://wp-9.iurii.test.monitoring.intellij.net/